### ISSUE TITLE
'Amahi Anywhere' not reachable error.

### ISSUE THREAD

**Issue by sanjitchak** [amahi/android#557] opened 2020-07-09 15:51 UTC
**Describe the issue**
Whenever I try to see "shares" in the android app, that error pops up.

**To Reproduce or Feature details**
1. Install amahi anywhere
2. Click on 'shares'
3. Wait
4. Error

**Expected behavior**
I expect to see my shares of my hda.

**Screenshots**
![Screenshot_20200709-210258](https://user-images.githubusercontent.com/20724062/87061899-f8182100-c229-11ea-8438-77a548345949.png)

**Smartphone (please complete as much of the following information as possible):**
 - Device: Asus max pro m1
 - OS: Android 9

**Additional context**
Maybe tell the user to install "Amahi Anywhere" on the STARTUP guide. And ask them to do the necessary settings in the "amahi anywhere", before using the android app. Like give them a small tutorial.

**Comment by chirag-jn** [comment] 2020-07-11 10:43
We need to revamp the documentation so that it's more user friendly and beginner-friendly.

**Comment by sanchi0204** [comment] 2020-07-12 19:41
What exactly needed to be done in this issue?

**Comment by chirag-jn** [comment] 2020-07-12 20:04
This issue is not something related to the android app but it's related to the Amahi server. Reinstalling Amahi Anywhere app on the Amahi 11 Server solves this bug but I'm not completely sure where the issue is.

**Comment by sanjitchak** [comment] 2020-07-12 21:01
Yes, more like an issue with "Amahi Anywhere" app in the server. Maybe the amahi anywhere service fails to start if no android is detected.

**Comment by chirag-jn** [comment] 2020-07-12 22:25
That seems to be a bug. Probably the process running the Amahi anywhere app enters the waiting state but isn't getting an appropriate handler to wake up again. Any thoughts on this @cpg ?

**Comment by chirag-jn** [comment] 2020-07-26 22:28
Since the related issue in `hda-ctl` is solved, we can close this issue.

**Closed as completed** 2020-07-27 04:38 UTC
Labels: good first issue
