### ISSUE TITLE
Unable to remove audio service from notification bar even when music is stopped

### ISSUE THREAD

**Issue by mohitsvnit** [amahi/android#348] opened 2018-03-23 04:32 UTC
When user play any audio then audio service or foreground activity start in notification bar.
Before few commits user was able to remove that notification and stop audio service when music was paused even if application was active.

But now I am unable to do that. Now to remove or kill audio service I have to forcefully kill application from application stack

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/12980721/37811446-4cfb0f4c-2e80-11e8-88c0-ed7beacfca27.gif)

I think user should able to stop audio service if music is stopped or paused. 
If this is not intentional, I would like to work on it.

**Comment by ArihantJain456** [comment] 2018-03-23 08:12
@mohitsvnit are you sure we were able to remove notification few commits before because this issue was also present in older Audio Service.
But now since you point it out, we can solve it.

**Comment by mohitsvnit** [comment] 2018-03-23 08:14
I don't remember exactly. So can't be sure.

**Comment by mohitsvnit** [comment] 2018-03-23 08:14
I am waiting for mentors to give their view on it. If they want it as it is or as I suggested.

**Comment by adi23arora** [comment] 2018-03-23 08:21
It's not a bug, I guess this is the general flow for an audio service. If we were able to do it previously then maybe it's resolved now.
And the thing you suggested that we should be able to stop it on pause, can be a good enhancement.

**Comment by mohitsvnit** [comment] 2018-03-24 18:58
@octacode please give your review.

**Comment by csoni111** [comment] 2018-04-04 14:03
This line [here](https://github.com/amahi/android/blob/c0f14ec6f3de36475ce7954756629ec63b7305b5/src/main/java/org/amahi/anywhere/util/MediaNotificationManager.java#L252)
```
.setOngoing(mPlaybackState.getState() == PlaybackStateCompat.STATE_PLAYING)
```
 was added for having the same functionality as mentioned in this issue. But unfortunately it doesn't work because the `startForeground()` call on the audio service overrides the `setOngoing(false)` on notification when paused.
You may go ahead and resolve this issue @mohitsvnit.

**Comment by mohitsvnit** [comment] 2018-04-04 14:18
sure @csoni111.

**Comment by mohitsvnit** [comment] 2018-04-12 04:43
@csoni111 I even removed `setOngoing(mPlaybackState.getState() == PlaybackStateCompat.STATE_PLAYING)` still foreground service is not removing on swiping. 
Do you have any idea where might be the problem is?

**Comment by csoni111** [comment] 2018-04-12 05:54
@mohitsvnit As I previously said `startForeground()` overrides the `setOngoing()` call. So you need to call `stopForeground(false)` when the audio is paused and again `startForeground()` on the service when audio is played.

```java
if (state.getState() == PlaybackStateCompat.STATE_PLAYING) {
    mService.startForeground(NOTIFICATION_ID, notification);
} else {
    mNotificationManager.notify(NOTIFICATION_ID, notification);
    mService.stopForeground(false);
}
``` 
Something like this ^ in [this place](https://github.com/amahi/android/blob/2398a193a49be71383961c4fe1cd18200015e9fc/src/main/java/org/amahi/anywhere/util/MediaNotificationManager.java#L82).

**Comment by adi23arora** [comment] 2018-04-12 22:59
@mohitsvnit You can also add a `Cancel` button to dismiss the notification (for pre-lollipop devices), using
```
notificationBuilder.setStyle(new NotificationCompat.MediaStyle()
    .setShowCancelButton(true)
    .setCancelButtonIntent(stopPendingIntent));
```
For reference, check [docs](https://developer.android.com/reference/android/support/v4/media/app/NotificationCompat.MediaStyle.html#setShowCancelButton(boolean)).

**Comment by mohitsvnit** [comment] 2018-04-14 18:57
Thank you @csoni111. It worked.

**Comment by ArihantJain456** [comment] 2018-05-24 22:47
@cpg Since the problem has been solved, I think we can close this issue.

**Comment by csoni111** [comment] 2018-07-26 17:49
Closing as resolved.

**Closed by csoni111** 2018-07-26 17:49 UTC
