### ISSUE TITLE
Recyclerview is not used in ServerFileFragment

### ISSUE THREAD

**Issue by mohitsvnit** [amahi/android#309] opened 2018-03-04 13:15 UTC
In [ServerFileFragment.java](https://github.com/amahi/android/blob/beta/src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java) `AbsListview` is used instead of `RecyclerView` which is advance version of `Listview` with losts of improvement in memory handling, recycling views etc.

**Comment by mohitsvnit** [comment] 2018-03-04 13:16
Right now I am working on issue [showing images in grid layout. Issue 156](https://github.com/amahi/android/issues/156). So I was thinking to solve this along with it as I have to modify ServerFileFragment for solving issue #156.

**Comment by adi23arora** [comment] 2018-03-04 13:34
@mohitsvnit This issue seems to be a duplicate of https://github.com/amahi/android/issues/147

**Comment by mohitsvnit** [comment] 2018-03-04 13:39
Actually this issue is sub-problem of issue #147. If I am not wrong issue #147 is for entire app. But in this issue I am going to touch only ServerFileFragment for now. Let's see what @cpg says. Else I will close this issue.

**Comment by octacode** [comment] 2018-03-06 09:55
Duplicate of #147. That issue is specifically for ServerFileFragment.java

**Closed by octacode** 2018-03-06 09:55 UTC
