### ISSUE TITLE
glide library crash

### ISSUE THREAD

**Issue by cpg** [amahi/android#202] opened 2017-04-14 06:13 UTC
we received a couple of glide crashes ..

```
Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
       at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
       at com.bumptech.glide.Glide.with(Glide.java:629)
       at org.amahi.anywhere.adapter.ServerFilesMetadataAdapter.bindFileMetadataView(ServerFilesMetadataAdapter.java:140)
       at org.amahi.anywhere.adapter.ServerFilesMetadataAdapter.bindView(ServerFilesMetadataAdapter.java:129)
       at org.amahi.anywhere.task.FileMetadataRetrievingTask.onPostExecute(FileMetadataRetrievingTask.java:74)
       at org.amahi.anywhere.task.FileMetadataRetrievingTask.onPostExecute(FileMetadataRetrievingTask.java:34)
       at android.os.AsyncTask.finish(AsyncTask.java:667)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:179)
       at android.app.ActivityThread.main(ActivityThread.java:6152)
...
```

**Comment by octacode** [comment] 2017-04-14 06:15
Sending a fix ASAP

**Comment by octacode** [comment] 2017-04-14 06:29
There seems to be an issue with the glide library itself. [The issue is having a won't fix tag.](https://github.com/bumptech/glide/issues/803) However there's a temporary fix to it until it's permanently resolved.

**Comment by csoni111** [comment] 2017-04-14 07:01
@octacode We may add a simple check for, if the activity is destroyed or running (or something like that) in the code. 
 **OR**
A better solution would be to add a interface/callback mechanism in the `ServerFilesMetadataAdapter` to interact with `FileMetadataRetrievingTask`, instead of what currently has been implemented _(using static [methods](https://github.com/amahi/android/blob/master/src/main/java/org/amahi/anywhere/adapter/ServerFilesMetadataAdapter.java#L125) and [calling](https://github.com/amahi/android/blob/master/src/main/java/org/amahi/anywhere/task/FileMetadataRetrievingTask.java#L74) them in onPostExecute in async task)_.

In my view, using static methods is not a good idea and should be replaced.

**Comment by csoni111** [comment] 2017-04-14 08:39
@octacode I have implemented the same in this [commit](https://github.com/csoni111/amahi-android/commit/9f8ff103f5a1afaec3677e5f83198f0b4c3c1946), are you working on something else for fixing this or should I open a pr?

**Comment by octacode** [comment] 2017-04-14 08:39
No issues! Go ahead

**Closed** 2017-04-14 20:59 UTC
