### ISSUE TITLE
best ways to handle libvlc

### ISSUE THREAD

**Issue by cpg** [amahi/android#17] opened 2017-03-04 11:13 UTC
We have discussed this before, and as we move forward, we will want to handle `libvlc` as smoothly as possible.

From my point of view (not being an Android expert), I see two main issues:

1. ~~compilation process for this app to bundle it in. we talked about using gradle to get it in. I am not sure if this is settled or not, though I see people compiling apks that crash with [1] when trying to stream video. I think we had a branch for this, but I don't know the status of it. Perhaps someone can review?~~ This task has been separated for #33.
1. the policy of when to invoke libvlc at run time. i don't know the current policy shipped, but the policy in iOS (which worked well), was: whitelist a default set of media types that will stream well in the main built-in video player in the platform (which means it will get Chromecast support, etc.), and for the rest of media types, fall back to vlc

[1] `Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/org.amahi.anywhere-2/lib/arm/libvlcjni.so: has text relocations`

**Comment by megabitdragon** [comment] 2017-03-04 13:44
I agree we need to use Android media library to handle all the media it can support. And fall back to libvlc for unsupported formats. 

The libvlc used by the app is outdated. I'll build the newest version against the latest sdk/ndk and make it available.

**Comment by dynamitechetan** [comment] 2017-03-04 17:24
libvlc does not even compile at first with gradle build.
Please fix it . I want to contribute to this project but I am having trouble building the source code.

**Comment by top-gun007** [comment] 2017-03-05 12:35
Can I work on it.

**Comment by top-gun007** [comment] 2017-03-05 12:37
It is working @dynamitechetan can you please elaborate problems are you facing.

**Comment by dynamitechetan** [comment] 2017-03-05 12:47
```
Error:Failed to resolve: org.videolan:libvlc:1.0.0
<a href="openFile:D:/app/amahi_andorid/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```
this is the gradle error

**Comment by octacode** [comment] 2017-03-05 14:15
@dynamitechetan even I had this same problem. What I did was that I downloaded and extracted the tar file mentioned in the instructions to build Amahi android app and pasted it extracted .m2 folder in my /home directory.

**Comment by dynamitechetan** [comment] 2017-03-05 14:27
I am on Windows. Where can I paste the file?

**Comment by megabitdragon** [comment] 2017-03-06 00:11
I created a new vlc2 branch that uses libvlc 2.1.1. I just added the library dependency without any other changes to the code. The application **will not build** as is. Code needs to be updated to account for the new SDK. You can check [this commit](https://goo.gl/BbyKmz) to get started.

**Comment by cpg** [comment] 2017-03-07 02:53
I created a separate issue, #33, for integration with libvlc 2.1.1 and we will keep this issue for dealing with policy changes as to when to invoke the vlc player.

**Comment by lakshyagupta21** [comment] 2017-03-07 04:21
@octacode I did the same thing that you suggested but still getting the same error in gradle while building the project in Studio.

**Comment by octacode** [comment] 2017-03-07 04:24
@lakshyagupta21 It worked for me pretty well. Try redownloading your forked repo, It might work.
Thanks

**Comment by lakshyagupta21** [comment] 2017-03-07 05:27
@octacode somehow it worked after restarting the studio. After that i am facing issues with API url ,id,proxy problem now how should i solve this issue?

**Comment by octacode** [comment] 2017-03-07 05:31
Follow the set of commands given on the Readme.md and I will mail you the url, proxy, client.id....

**Comment by lakshyagupta21** [comment] 2017-03-07 08:43
@octacode Thanks for helping me out. Send details to lakshyagpt2009@gmail.com

**Comment by lakshyagupta21** [comment] 2017-03-07 18:20
The error shown in the issue is coming only in android versions > 21 below this API LEVEL it is working fine(Checked for API LEVEL 18 and 19).

**Comment by doomers** [comment] 2017-03-08 03:07
@octacode i am also having the same problem.
 please also mail me the url, proxy, client.id. etc.
my email_id: rahul40800@gmail.com
Thanks in advance

**Comment by csoni111** [comment] 2018-03-13 08:38
@cpg Closing this as resolved.

We now have the following setup:
- All videos are played using libvlc player.
- The native android video player code is there in the app, but it is never called for playing videos.
- Chromecast support is there with libvlc player itself. #289

**Closed by csoni111** 2018-03-13 08:38 UTC
Labels: enhancement
